### PR TITLE
Fix for the Unauthorized File Access vulnerability [huntr]

### PR DESCRIPTION
**Pull request by mufeedvh**
Fix for the Unauthorized File Access vulnerability. This fix prevents access to symlinks pointing to files outside of the project's base directory.

@mufeedvh on huntr.dev

### CODE REVIEW

**Review by toufik-airane — APPROVED** [review]
LGTM 👍

**Comment by JamieSlome** [comment]
Congratulations @mufeedvh. You are the successful huntr!

Thank you for submitting your fix - we have approved your pull request and will merge your commits into our master branch. 

If you have any questions, please respond in the comments section. Your bounty is on its way - keep hunting.

**Comment by toufik-airane** [comment]
Congratulation @mufeedvh. Awesome work! 👏

**Comment by mufeedvh** [comment]
Thank You @JamieSlome @toufik-airane :heart::smiley:

**Pull request merged**
